---
- name: Distribucio clau pub
  hosts: webservers
  become: true
  vars_files:
    - defaults.yml

  tasks:
    - name: Afegir la clau p√∫blica
      ansible.posix.authorized_key:
        user: "{{ created_username }}"
        state: present
        key: "{{ lookup('file', '/home/ec2-user/.ssh/ansiblePGL.pub') }}"
